name: items_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  get_it: ^7.7.0
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  floor: ^1.4.0
  dio: ^5.5.0+1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  floor_generator: ^1.4.0
  build_runner: ^2.1.2
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/log/logo.png"
  min_sdk_android: 21 
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/log/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/log/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/log/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/log/
    - assets/icons/
flutter_native_splash:
  color: "#ffffff"
  image: "assets/log/logo.png"
  color_dark: "#ffffff"
  image_dark: "assets/log/logo.png"
  android_gravity: center
  android_12:
    image: "assets/log/logo.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/log/logo.png"
    icon_background_color_dark: "#ffffff"