name: items_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  get_it: ^7.7.0
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  floor: ^1.4.0
  dio: ^5.5.0+1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  floor_generator: ^1.4.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
