name: Android Release

on:
  push:
    branches: [ "main" ,"Dev","Test"]

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x" 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.3"
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get

      - name: flutter run splash-screen
        run: dart run flutter_native_splash:create
  staging:
    runs-on: ubuntu-latest
    needs: [develop]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x" 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.3"
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get

      - name: flutter run splash-screen
        run: dart run flutter_native_splash:create

      - name: flutter run test
        run: flutter run test
      